graph LR

%% ======================================
%% QUASI-STATIC
%% ======================================

%% ===================
%% Lemma
%% ===================

Lemma["Lemma - Lemme<br>{Morphemes[]} Morphemes - Morphèmes"]

Lemma --> Noun["Noun - Nom<br>{boolean} animate - Animé"]
Lemma --> Determiner["Determiner - Déterminant"]
Lemma --> Pronoun["Pronoun - Pronom"]
Lemma --> Verb["Verb - Verbe"]
Lemma --> Adverb["Adverb - Adverbe"]
Lemma --> Adjective["Adjective - Adjectif"]
Lemma --> Interjection["Interjection - Interjection"]
Lemma --> Preposition["Preposition - Préposition"]
Lemma --> Conjunction["Conjunction - Conjonction"]
Lemma --> Numeral["Numeral - Nombre"]
Lemma --> Other["Other - Autre"]

%% ===================
%% Inflection
%% ===================

Inflection["Inflection - Flexion<br>{Lemma} lemma - Lèmme<br>{Morphemes[]} Morphemes - Morphèmes"]

  Inflection --> Declension["Declension - Déclinaison<br>{Number} number - Nombre<br>{Gender} gender - Genre"]
  Inflection --> Conjugation["Conjugation - Conjugaison"]

%% declinaison ou conjugaison
%% number: singular, plural, invariable
%% gender: masculine, feminine, invariable
%% https://repository.ortolang.fr/api/content/morphalou/3/LISEZ-MOI.html

%%'abbreviation','auxiliary','impersonal','defective','onomatopoeia','negation','determinant','adjective','demonstrative','possessive','personal','relative','indefinite','interrogative','exclamatory','definite','negative','subordination' et 'coordination'

  Noun --> CommonNoun["CommonNoun - Nom commun<br>{boolean} countable - Dénombrable<br>{boolean} concrete - Concret<br>{Gender} gender - Genre<br>{boolean} collective - Nom collectif"]
    CommonNoun --> CommonStandardNoun["CommonStandardNoun - Nom commun standard<br>e.g. maison"]
    CommonNoun --> CommonCompoundNoun["CommonCompoundNoun - Nom commun composé<br>{Noun[]} nouns - Noms<br>{''|' '|'-'} junction - Jonction<br>e.g.  chou-fleur"]
    CommonNoun --> CommonComplexNoun["CommonComplexNoun - Nom commun complexe<br>{Noun[]} nouns - Noms<br>{''|' '|'-'} junction - Jonction"]
      CommonComplexNoun --> CommonComplexSyntagmaNoun["CommonComplexSyntagmaNoun - Nom commun complexe syntagme<br>e.g. grand-chose"]
      CommonComplexNoun --> CommonComplexExpressionNoun["CommonComplexExpressionNoun - Nom commun complexe expression complète<br>e.g. je-ne-sais-quoi"]

  Noun --> ProperNoun["ProperNoun - Nom propre<br>e.g. Nicolas"]

%% Verb
%% mood: infinitive, indicative, participle, subjunctive, imperative, conditional
%% tense: present, futur, past, imperfect, simplePast
%% person: firstPerson, secondPerson, thirdPerson
%% number: singular, plural, invariable

  Determiner --> DeterminerArticle

%% ===================
%% Locution
%% ===================
%% adverbiales, verbale, nominales, prépositionnelles

%% ou groupe nominal (éducation physique)

%% ===================
%% NominalGroup
%% ===================

NominalGroup["NominalGroup - Groupe nominal<br>{Lemme[] lemmas - Liste de lemmes"]

%% ===================
%% Morpheme
%% ===================


Morpheme["Morpheme - Morphème<br>{boolean} free - Libre (existe en tant que lemme) sinon lié"]

  %% Classe fermée
  Morpheme --> GrammaticalMorpheme["GrammaticalMorpheme - Grammème<br>e.g. tu, à, et, etc."]
    GrammaticalMorpheme --> Affix["Affix - Affixe<br>{string} content - Contenu<br>{string=} meaning - Signification"]
      Affix --> Prefix["Prefix - Prefixe"]
      Affix --> Suffix["Suffix - Suffixe"]
  %% Classe ouverte
  Morpheme --> Lexeme["Lexeme - Lexème<br>{string} content - Contenu"]

%% Un autre exemple est couraient, qui est composé de cour- « courir », -ai- (marque de l'imparfait) et -ent (3e personne du pluriel à l'écrit, « ils »)
%% Cet exemple est sans segmentation de mot : pomme de terre n'est pas composé de trois morphèmes mais bien d'un seul morphème, qui contient la signification « pomme de terre », le légume en question.
%% https://books.openedition.org/pup/485?lang=fr
%% http://archive.sfl.cnrs.fr/sites/sfl/IMG/pdf/corr-Res-Sem1-12010.pdf

%% ===================
%% Phoneme
%% ===================

Phoneme["Phoneme - Phonème<br>{string} content - Contenu"]

%% ===================
%% Number
%% ===================

Number["Number - Nombre"]
Number --> Singular["Singular - Singulier"]
Number --> Plural["Plural - Pluriel"]
Number --> Invariable["Invariable - Invariable en nombre"]

%% ===================
%% Gender
%% ===================

Gender["Gender - Genre"]
Gender --> Masculine["Masculine - Masculin"]
Gender --> Feminine["Feminine - Feminin"]
Gender --> Invariable["Invariable - Genre invariable"]

%% ===================
%% Function
%% ===================

Function["Function - Fonction<br>{Group} related - Par rapport au groupe"]

  Function --> Subject["Subject - Sujet"]
  Function --> DirectObject["DirectObject - Complément d'objet direct"]
  Function --> IndirectObject["IndirectObject - Complément d'objet indirect"]
  Function --> ObjectComplement["ObjectComplement - Complément"]
  Function --> ObjectOfPreposition["ObjectOfPreposition - ObjectOfPreposition"]
  Function --> PedicateNominative["PedicateNominative - Attribut"]
  Function --> Appositive["Appositive - Apposition"]

%% Les fonctions au sein de la proposition
%% Subject - Sujet
%% ObjectComplement - Complément d'objet
  %% direct
  %% second
  %% indirect
%% PedicateNominative - Attribut
  %% Le chat est *mon animal préféré*
  %% Le chat est <b>mon animal préféré</b>
  %% The cat is *my favourite animal*
%% ? - Complément circonstanciel
%% ? - Complément d'agent

%% Les fonctions au sein d'un constituant
%% Epithet - Épithète
%% Appositive - Apposition
%% ? - Complément

%% ======================================
%% DYNAMIC
%% ======================================

%% ===================
%% Group
%% ===================

Group["Group - Groupe<br>{Group} parent - Groupe parent<br>{Lemma[]} - Liste de lemmes<br>{Function} - Fonction du groupe"]

%%TDD Resources: fane, moeurs, un=une extra-terrestre: invariable, abimer=abîmer